### PR TITLE
DAT-13904 test ssh pub key

### PR DESCRIPTION
**Pull request by jandroav**
https://datical.atlassian.net/browse/DAT-13904

### CODE REVIEW

**Review by jnewton03 — APPROVED** [review]
looks good @jandroav !  

Question:  Do  we need to pull in any upstream changes from the base repo?  At first glance I didn't see changes in `terraform-single` so I don't think we do.  Also what do you think about this being a separate repo?  Should it be folded into our infra repo as a submodule or something?  Trying to figure out best practice.

**Comment by jandroav** [comment]
> 

It seems the master branch is outdated with the base repo but I would move it to our infra repo. I have some ideas in my own backlog and I was thinking about this:

* https://medium.com/@ECD3/creating-reusable-terraform-modules-for-azure-and-best-practices-ba347d60e93e

I think at some point we need to reconsider if it is worth having our modules in a separate repo so we can reference them as:

```terraform
module "example" {
  source = "git::https://github.com/liquibase/infrastructure-modules.git//infrastructure-ibm-cloud"
}
```

We could save a lot of time when planning things

**Comment by jnewton03** [comment]
@jandroav I like it!  Lets get that added to the backlog for sure.

**Comment by jandroav** [comment]
@jnewton03 I am going to close this PR. The new PR is here: https://github.com/Datical/liquibase-infrastructure/pull/867

**Pull request closed without merging**
